In [3]:
import numpy as np

# 数组跟数
arr = np.array([1,2,3,4])

In [4]:
arr + 1

array([2, 3, 4, 5])

In [5]:
# 数组跟数组
# 广播机制，限制一些数组之间的一些运算操作
"""a:[2,3]  b:[2,1]"""
a = np.array([[4,5,6], [7,8,9]])
b = np.array([[2], [2]])

In [6]:
a * b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [7]:
# 矩阵，得出学生综合成绩
score = np.array([[80,86],
[82,80],
[85,78],
[90,90],
[86,82],
[82,90],
[78,80],
[92,94]])

In [9]:
# 比例
percent = np.array([0.3, 0.7])

In [11]:
score * percent

array([[24. , 60.2],
       [24.6, 56. ],
       [25.5, 54.6],
       [27. , 63. ],
       [25.8, 57.4],
       [24.6, 63. ],
       [23.4, 56. ],
       [27.6, 65.8]])

In [15]:
 score_mat = np.mat(score)

In [16]:
percent = np.array([[0.3],[0.7]])

In [17]:
score_mat * percent 

matrix([[84.2],
        [80.6],
        [80.1],
        [90. ],
        [83.2],
        [87.6],
        [79.4],
        [93.4]])