In [4]:
import numpy as np

In [6]:
# 数组创建 0， 1
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# 从已有的数据中创建
a = np.array([[1,2,3], [4,5,6]])
arr1 = np.array(a)
arr2 = np.asarray(a)

In [8]:
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6]]), array([[1, 2, 3],
        [4, 5, 6]]))

In [9]:
# 有什么不同
# asarray：依旧是引用原来的数组，所以会随原有数组变化
# array：相当于创建了一个新的数组
a[1] = 10

In [10]:
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6]]), array([[ 1,  2,  3],
        [10, 10, 10]]))

In [11]:
# 生成等间距的数组
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [12]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [13]:
# 创建一个随机数组
# 均匀分布
np.random.uniform(0,100)

70.3933676105279

In [15]:
# 正态分布
np.random.normal(1.75, 0.1, [10,10])

array([[1.82202479, 1.68790292, 1.71903333, 1.5103398 , 1.75406319,
        1.72379464, 1.85622789, 1.64656184, 1.65116946, 1.68290582],
       [1.77567778, 1.69019667, 1.85463069, 1.90955377, 1.85696871,
        1.70508657, 1.61309072, 1.67493874, 1.60869489, 1.84492891],
       [1.65245145, 1.70092775, 1.6455139 , 1.79710855, 1.69172119,
        1.7137671 , 1.71486356, 1.71859441, 1.74993174, 1.64345357],
       [1.75835128, 1.92909717, 1.86730796, 1.82673322, 1.710746  ,
        1.77373811, 1.62815822, 1.7053722 , 1.76722843, 1.67108537],
       [1.76701127, 1.86328726, 1.80766184, 1.68578053, 1.81133937,
        1.88497773, 1.81568136, 1.72493954, 1.54924495, 1.78283488],
       [1.98105899, 1.76184196, 1.74473379, 1.83503623, 1.74526067,
        1.69535641, 1.7555744 , 1.87388143, 1.63460912, 1.81515961],
       [1.68195801, 1.69574645, 1.55754136, 1.78771721, 1.83988127,
        1.77074759, 1.9617182 , 1.67140482, 1.63281193, 1.65823801],
       [1.66545988, 1.71671637, 1.6860823